### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by AldeRoberge** [apkd/Medicine#4]
Am I missing something? It doesn't seem to work...

![image](https://user-images.githubusercontent.com/4276275/202594959-f34a5fb8-601c-46b2-8e47-4c6ca14deba0.png)

Failed to initialize CanvasGroup _canvasGroup in component HommeTonnerre.Scripts.Game.UI.Dialogue.DialogPanel.

![image](https://user-images.githubusercontent.com/4276275/202594995-3316151c-c054-4d1d-8265-7b566eb3d54b.png)

**Comment by AldeRoberge** [comment]
I should have double checked, I got confused between CanvasGroup and CanvasRenderer. My bad! It works.

**Comment by apkd** [comment]
Thanks, great to hear you managed to get it working!
